services:
  - type: web
    name: marco-life-copilot
    env: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn marco_bot:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    autoDeploy: true
    pullRequestPreviewsEnabled: true
